<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.42.3 (20191010.1750)
 -->
<!-- Title: gr Pages: 1 -->
<svg width="134pt" height="44pt"
 viewBox="0.00 0.00 134.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
<title>gr</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-40 130,-40 130,4 -4,4"/>
<!-- 2 -->
<g id="node1" class="node">
<title>2</title>
<ellipse fill="none" stroke="black" cx="18" cy="-18" rx="18" ry="18"/>
<text text-anchor="middle" x="18" y="-14.3" font-family="Times,serif" font-size="14.00">2</text>
</g>
<!-- 3 -->
<g id="node2" class="node">
<title>3</title>
<ellipse fill="none" stroke="black" cx="108" cy="-18" rx="18" ry="18"/>
<text text-anchor="middle" x="108" y="-14.3" font-family="Times,serif" font-size="14.00">3</text>
</g>
<!-- 2&#45;&gt;3 -->
<g id="edge1" class="edge">
<title>2&#45;&gt;3</title>
<path fill="none" stroke="black" d="M36.39,-18C48.76,-18 65.63,-18 79.78,-18"/>
<polygon fill="black" stroke="black" points="79.95,-21.5 89.95,-18 79.95,-14.5 79.95,-21.5"/>
<text text-anchor="middle" x="63" y="-21.8" font-family="Times,serif" font-size="14.00">5/5</text>
</g>
</g>
</svg>
